### ISSUE TITLE
'Beam' object has no attribute '_parameters'

### ISSUE THREAD

**Issue by jolindbe** [aplpy/aplpy#58]
A code that worked in previous versions now (in 0.9.8) produces the error in the title. The code is as follows:

gc.add_beam(major=5.98/3600,minor=2.89/3600,angle=8.3,corner='bottom right')
gc.beam.show(major=5.98/3600,minor=2.89/3600,angle=8.3,corner='bottom right',frame=False)
gc.beam.set_color('k')

The error occurs on the third line.
