### ISSUE TITLE
Problem with png->wcs conversion in FITSFigure.

### ISSUE THREAD

**Issue by imckstewart** [aplpy/aplpy#330]
I'm running under Fedora 25. My pyAVM version is 0.9.2. If I (actually I am trying to get this to work for a colleague) try to plot a png figure via FITSFigure using the following code
```
import pylab as pl
import aplpy

rgb_cube_png = "e2e_outflow_SiO_redblue_cycle3green_asinhgreen.png"

pl.rcParams['font.size'] = 18
fig1 = pl.figure(1)
fig1.clf()
F = aplpy.FITSFigure(rgb_cube_png, figure=fig1)
#etc
```
I get the error
```
Traceback (most recent call last):
  File "test_ims.py", line 12, in <module>
    F = aplpy.FITSFigure(rgb_cube_png, figure=fig1)
  File "<string>", line 2, in __init__
  File "/home/ims/.local/lib/python2.7/site-packages/APLpy-1.2.dev0-py2.7.egg/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/home/ims/.local/lib/python2.7/site-packages/APLpy-1.2.dev0-py2.7.egg/aplpy/core.py", line 201, in __init__
    raise aue.AstropyDeprecationWarning('WCS no longer stores information about NAXISn '
astropy.utils.exceptions.AstropyDeprecationWarning: WCS no longer stores information about NAXISn so it is not possibly to instantiate a FITSFigure from WCS alone
```
If I look in the code I see that at line 180 of core.py the pyAVM module is used to convert the 'data' image dimensions to a WCS object. But then the code complains at line 192 that the WCS object it just itself made is not adequate.

BTW the PNG image was made via aplpy.make_rgb_image().

**Comment by keflavich** [comment]
This is Issue #284.  Try using this branch:
https://github.com/keflavich/aplpy/tree/my_master_mar2016
which incorporates a couple other changes that are important for the script you're running.

**Comment by imckstewart** [comment]
Now I get
```
ims@quitor:~/temp/ciriaco$ python test_ims.py 
Traceback (most recent call last):
  File "test_ims.py", line 11, in <module>
    F = aplpy.FITSFigure(rgb_cube_png, figure=fig1)
  File "<string>", line 2, in __init__
  File "/home/ims/.local/lib/python2.7/site-packages/APLpy-1.2.dev0-py2.7.egg/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/home/ims/.local/lib/python2.7/site-packages/APLpy-1.2.dev0-py2.7.egg/aplpy/core.py", line 184, in __init__
    data = AVM.from_image(data,xmp_packet_index=xmp_packet_index).to_wcs()
TypeError: from_image() got an unexpected keyword argument 'xmp_packet_index'
```

**Comment by keflavich** [comment]
Right, sorry, that is yet another unmerged commit.  See the linked pyavm branch.  For now, this branch: https://github.com/keflavich/pyavm/tree/multiple-xmp-packets ought to work, but we really need to get those fixes merged.

**Comment by imckstewart** [comment]
Ok that seems to work... thanks.

**Comment by jensmelinder** [comment]
I have exactly the same problem. My code was working fine with astropy 1.3 and older versions of aplpy/pyavm (1.0/0.9.1), but quit working after updating to the current release versions.

Using keflavich's linked commits (for both aplpy and pyavm) does not help, I still get the second error (... unexpected keyword...). Maybe the update to astropy 1.3.2 broke this fix somehow?

**Comment by astrofrog** [comment]
This should now all be fixed, as APLpy 2.0 requires a recent PyAVM version.
