### ISSUE TITLE
aplpy does not seem to work with matplotlib 3.0

### ISSUE THREAD

**Issue by johnarban** [aplpy/aplpy#403]
This is there error returned upon running
`gc = aplpy.FITSFigure('file.fits')`
error:
`"get_tightbbox() got an unexpected keyword argument 'bbox_extra_artists'" 1`

This is with the newest version of matplotlib 3.0.1 (which has  caused no end of problems, so I switched back to 2.2.3, and aplpy works again)
